// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5FeniyjiYkeJFvod95eLIUd4YZJ3LWVQ',
    appId: '1:33027890632:web:ec059cbdbb37d7169074fd',
    messagingSenderId: '33027890632',
    projectId: 'splitly-d5634',
    authDomain: 'splitly-d5634.firebaseapp.com',
    storageBucket: 'splitly-d5634.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQrEXyBlquiq7VjhXIlHq3MoGiaZ8pJ2A',
    appId: '1:33027890632:android:d0d2598f33366b229074fd',
    messagingSenderId: '33027890632',
    projectId: 'splitly-d5634',
    storageBucket: 'splitly-d5634.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7GqzoyVVSkre-g69rdf-mbqiE8PxdTQ',
    appId: '1:33027890632:ios:6194874db6a751869074fd',
    messagingSenderId: '33027890632',
    projectId: 'splitly-d5634',
    storageBucket: 'splitly-d5634.firebasestorage.app',
    iosBundleId: 'com.example.splitly',
  );
}
